runtime: nodejs20
entrypoint: yarn start

env_variables:
  MONGODB_URI: # MongoDB URI
  # Add any other environment variables needed by your application

# instance_class: F2

# automatic_scaling:
#   target_cpu_utilization: 0.65
#   max_instances: 30


handlers:
- url: /api/.*
  script: auto
