runtime: nodejs20
entrypoint: yarn start

env_variables:
  MONGODB_URI: "mongodb+srv://azeez:%40%40Azeez27@cluster0.xl7msos.mongodb.net/eazy-cart"
  # Add any other environment variables needed by your application

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 32

handlers:
- url: /api/.*
  script: auto
